name = "mcsr-pb-display"
main = "./src/index.ts"
compatibility_date = "2026-03-14"
compatibility_flags = [
  "nodejs_compat",
  "enable_request_signal",
  "request_signal_passthrough"
]
workers_dev = true

[[durable_objects.bindings]]
name = "RANKED_THROTTLE"
class_name = "RankedThrottle"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "RankedThrottle" ]

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "./public/"
binding = "ASSETS"
