name = "mcsr-pb-display"
main = "./src/index.ts"
compatibility_date = "2025-09-09"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "./public/"
binding = "ASSETS"
